### ISSUE TITLE
live view socket error in socket.js

### ISSUE THREAD

**Issue by building39** [elixir-wallaby/wallaby#500]
## Issue

phantomjs 2.1.1
chrome 79
phoenix 1.4.11
phoenix_live_view 0.4.1
elixir 1.9.4
otp 22

When running a test that visits a page ( in this case, a simple login page) the test fails with:
```** (Wallaby.JSError) There was an uncaught javascript error:
     
     Error: 
           a phoenix Socket must be provided as the second argument to the LiveSocket constructor. For example:
     
               import {Socket} from "phoenix"
               import {LiveSocket} from "phoenix_live_view"
               let liveSocket = new LiveSocket("/live", Socket, {...})
           
       e (undefined:1)
     
     code: |> sign_in_admin("admin@example.com", "123456789")
     stacktrace:
       (wallaby) lib/wallaby/phantom/logger.ex:7: Wallaby.Phantom.Logger.parse_log/1
       (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:783: Enum.each/2
       (wallaby) lib/wallaby/driver/log_checker.ex:12: Wallaby.Driver.LogChecker.check_logs!/2
       (wallaby) lib/wallaby/browser.ex:924: Wallaby.Browser.visit/2
```

**Comment by building39** [comment]
Offending code:
```Wallaby.Browser.visit(session, "http://www.example.com:5000/admin")
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_email"), with: email)
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_password"), with: password)
    |> Wallaby.Browser.click(Wallaby.Query.button("login-form__sign-in-button"))
```

**Comment by building39** [comment]
```Wallaby.Browser.visit(session, "http://www.example.com:5000/admin")
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_email"), with: email)
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_password"), with: password)
    |> Wallaby.Browser.click(Wallaby.Query.button("login-form__sign-in-button"))
```

**Comment by building39** [comment]
One more try:
```
Wallaby.Browser.visit(session, "http://www.example.com:5000/admin")
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_email"), with: email)
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_password"), with: password)
    |> Wallaby.Browser.click(Wallaby.Query.button("login-form__sign-in-button"))
```

**Comment by building39** [comment]
Offending code:
```
Wallaby.Browser.visit(session, "http://www.example.com:5000/admin")
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_email"), with: email)
    |> Wallaby.Browser.fill_in(Wallaby.Query.text_field("session_password"), with: password)
    |> Wallaby.Browser.click(Wallaby.Query.button("login-form__sign-in-button"))
```

**Comment by aaronrenner** [comment]
@building39 Thanks for opening the issue!

At first glance it seems like phantom is seeing a JS error, which is outside of wallaby's control. If you open up the site and follow these steps in Chrome dev tools, do you see the same issue? Another option might be to switch to ChromeDriver.

I'll try to look into this deeper when I have a chance. If you have a moment and could put together a tiny app that reproduces the same behavior, that would be super helpful. Otherwise, I'll see if I can put something together. Thanks!

**Comment by building39** [comment]
The problem was simply that I didn't recompile the fixed assets. Once I did that, the problem went away. You can close this issue.
