### ISSUE TITLE
Wallaby requires bash

### ISSUE THREAD

**Issue by mhanberg** [elixir-wallaby/wallaby#576]
## Issue

The wrapper script that opens chromedriver currently uses bash, if you are running alpine in CI, Wallaby will mysteriously fail because alpine does not come with bash out of the box.

## Solution

The wrapper script should not require bash or there should be some documentation around this Gotcha.

**Comment by oestrich** [comment]
This is the error message that comes up

```
** (FunctionClauseError) no function clause matching in Keyword.fetch!/2
    (elixir 1.11.2) lib/keyword.ex:417: Keyword.fetch!(nil, :os_pid)
    (wallaby 0.26.2) lib/wallaby/chrome/chromedriver/server.ex:101: Wallaby.Chrome.Chromedriver.Server.handle_continue/2
    (stdlib 3.13.2) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13.2) gen_server.erl:431: :gen_server.loop/7
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start_chromedriver}
18:55:14.201 [error] GenServer Wallaby.Chrome.Chromedriver terminating
** (stop) {:exit_status, 127}
Last message: {#Port<0.34>, {:exit_status, 127}}
```
