### ISSUE TITLE
Tests are failing on Heroku CI

### ISSUE THREAD

**Issue by jorbs** [elixir-wallaby/wallaby#598]
## Issue

All my wallaby tests are failing on Heroku CI, but they run just fine in my local.

To debug the error I tried to check the browser file log with `js_logger` option enabled (it results in a empty file) and viewed the screenshots (all of them are blank images).

The error in Heroku CI:
```
  1) feature login to the application as external user (MyAppWeb.Acceptance.LoginTest)
     test/my_app/acceptance/login_test.exs:22
     ** (Wallaby.QueryError) Expected to find 1, visible link 'Sign In' but 0, visible links were found.
     
     code: |> click(link("Sign In"))
     stacktrace:
       (wallaby 0.28.0) lib/wallaby/browser.ex:777: Wallaby.Browser.find/2
       (wallaby 0.28.0) lib/wallaby/browser.ex:761: Wallaby.Browser.find/3
       test/my_app/acceptance/login_test.exs:26: (test)
```

## Details

Elixir: 1.12.1
Erlang: 23.1.4
OS: Heroku
Webdriver (selenium, chromedriver, geckodriver, etc): chrome driver from https://github.com/heroku/heroku-buildpack-chromedriver -- automatically added to PATH.
Browser (Chrome, Firefox, Safari, etc): Google Chrome from https://github.com/heroku/heroku-buildpack-google-chrome
Local or CI: Heroku CI

## Test Code & HTML

test.exs:
```
# GOOGLE_CHROME_BIN is added by Google Chrome Heroku buildpack
if System.get_env("GOOGLE_CHROME_BIN") do
  config :wallaby,
    otp_app: :my_app,
    chromedriver: [
      binary: System.get_env("GOOGLE_CHROME_BIN")
    ]
else
  config :wallaby, otp_app: :my_app, screenshot_on_failure: true
end
```

login_test.exs:
```
defmodule MyAppWeb.Acceptance.LoginTest do
  use ExUnit.Case
  use Wallaby.Feature

 #...

 feature "login to the application as an external user", %{session: session} do
    session
    |> visit("/")
    |> set_cookie(:auth, Jason.encode!(@app_user_auth))
    |> click(link("Sign In"))
    |> find(css(".main-container"), &assert(has?(&1, css(".dashboard-content"))))

    user = MyApp.Repo.get_by(MyApp.User, email: @app_user_auth[:email])

    assert user.uid == @app_user_auth[:uid]
    assert user.first_name == @app_user_auth[:first_name]
    assert user.last_name == @app_user_auth[:last_name]
    assert user.email == @app_user_auth[:email]
  end
end
```

**Comment by jorbs** [comment]
I've fixed this! The error was happening because I forgot to compile the assets.
